spring.application.name=website_ara_and_rody
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=GFGF18101961
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
#batch_size
spring.jpa.properties.hibernate.jdbc.batch_size=20


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=ee7e7b7d1288ceeb427cbc933ad7d4223a37d7d6731da8311bd381074deb6f2d

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=9197195@gmail.com
spring.mail.password= suhjonzyinoerula

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
