spring.application.name=website_ara_and_rody

server.address=0.0.0.0
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=GFGF18101961

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20

server.error.include-message=always

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=ee7e7b7d1288ceeb427cbc933ad7d4223a37d7d6731da8311bd381074deb6f2d

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=9197195@gmail.com
spring.mail.password=suhjonzyinoerula
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.url=http://26.77.152.228:5173

# CORS Configuration
#spring.web.cors.allowed-origins=http://26.77.152.228:5173
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true
#spring.web.cors.max-age=3600

# ?????????????? ???????????
# ?????????????? ??????????? ??? ???????????
# === ?????????????? ??????????? ??? ??????? ???????/CORS ??????? ===
# ??????????? ????????? CORS
logging.level.org.springframework.web.cors=TRACE
# ????????? ???? ??????? ???????? Spring Security
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
# ??????????? ??????? ??????? ? DispatcherServlet
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
# ??????????? ???? ? ?????????? ???????? (???? ???????? ??? CommonsRequestLoggingFilter)
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
# ??????????? ?? ?????? Tomcat/Catalina (???????? ??????????)
logging.level.org.apache.catalina.filters=DEBUG
logging.level.org.apache.coyote.http11=DEBUG