### Регистрация нового пользователя
POST http://localhost:9090/api/users/registration
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111",
  "name": "Иван",
  "secondName": "Иванов",
  "surName": "Иванович"
}

### Подтверждение регистрации (код из письма)
POST http://localhost:9090/api/users/confirm-registration?code=983365

### Аутентификация (вход)
POST http://localhost:9090/api/singIn/auth
Content-Type: application/json

{
  "email": "4057163@mail.ru",
  "password": "11111111"
}

### 1. Создание поста (требуется JWT-токен в заголовке Authorization)
POST http://localhost:9090/api/post/creatPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJpYXQiOjE3NzY4Njg3OTgsImV4cCI6MTc3Njg2OTY5OCwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.JA5NWgspN4Ra-JNiRArquo8liO2LpcS7wDaUNhTlhTYlO3zy4iGnaeX9lynWLmC3

{
  "title": "Заголовок первого поста",
  "text": "Текст поста, может быть длинным"
}

### 2. Создание комментария к посту с ID = 1 (требуется JWT-токен)
POST http://localhost:9090/api/comment/create/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI0MDU3MTYzQG1haWwucnUiLCJpYXQiOjE3NzY4NjkyODEsImV4cCI6MTc3Njg3MDE4MSwidXNlcklkIjoxLCJyb2xlcyI6WyJVU0VSIl19.tQQpWfhtj_Uaz4V3bZzDblAPSFFQpowsvkE0aljiMTIfofQog-E0F0rUEN_j1l7t

{
  "comment_text": "Отличный пост!"
}
